"""Agregar columnas payment_type y payment_detail a Reservation

Revision ID: 82bcd2d4fc70
Revises: 
Create Date: 2025-09-16 09:47:47.345714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bcd2d4fc70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_detail', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('payment_detail')
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
